using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Net.Mail;
using System.Web.Http;
using System.Web.Http.Cors;
using TaskAPI.BOL;
using TaskAPI.Models;

namespace TaskAPI.Controllers
{
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    public class SendMailController : ApiController
    {
       SubCategory_Models objModels = new SubCategory_Models();

        [HttpPost]
        // HELP SUPPORT BIND
        /// <summary>
        /// Visa Help support
        /// </summary>
        /// <param name="loggedInUserId">Request submit by Id</param>
        /// <param name="Remarks">Message</param>
        /// <param name="loggedInUserMailId">Request by mail Id</param>
        /// <returns></returns>
        public string PostVisaHelpDeskSupport(string dataParam, HelpSupportModel _helpSupportModel)
        {
            string data = string.Empty;
            string returnData = string.Empty;
            try
            {
                string sendmailResponse = sendMailToUser(_helpSupportModel);
                if (sendmailResponse == "1")
                {
                    _helpSupportModel.IsMailSendToUser = true;
                    returnData = new MailSent().VisaHelpDeskSupport(_helpSupportModel);
                }
                else
                {
                    _helpSupportModel.IsMailSendToUser = false;
                    returnData = "-1";

                }
                data = JsonConvert.SerializeObject(returnData);
            }
            catch (Exception Ex)
            {
                data = JsonConvert.SerializeObject(Ex.Message);
            }
            return data;
        }
        private string sendMailToUser(HelpSupportModel _helpSupportModel)
        {
            string returnMsg = string.Empty;
            try
            {
                MailMessage mail = new MailMessage();
                SmtpClient SmtpServer = new SmtpClient(MailConstant.smtpserver);
                if (_helpSupportModel.RequestByMailId != "" && _helpSupportModel.RequestByMailId != null)
                {
                    mail.From = new MailAddress(_helpSupportModel.RequestByMailId);
                }
                else
                {
                    mail.From = new MailAddress("nomailfound@nomail.com");
                }
                mail.To.Add(MailConstant.tomailId);
                mail.CC.Add(MailConstant.ccMailId);
                mail.CC.Add(MailConstant.ccMailId2);
                mail.Subject = MailConstant.visahelpsubject + " " + DateTime.Now + " by " + _helpSupportModel.RequestByUserName;
                mail.Body = "<p>Hi Touchstone Support,</p><p>Please see the details below regarding the help generated by:</p><p>&nbsp;</p><p>Request By: " + _helpSupportModel.RequestByUserName + "&nbsp;</p><p>Extension Number: " + _helpSupportModel.RequestByExtNo + "</p><p>Role: " + _helpSupportModel.RequestByRoleName + "</p><p>Center:" + _helpSupportModel.RequestByCenterHeadName + "</p><p>Campus:" + _helpSupportModel.RequestByCenterName + "</p><p>Remarks:" + _helpSupportModel.Remarks + "</p><p>Thanks</p>";
                mail.IsBodyHtml = true;
                SmtpServer.Port = MailConstant.portno;
                SmtpServer.UseDefaultCredentials = false;
                SmtpServer.Credentials = new System.Net.NetworkCredential(MailConstant.networkcredentialsUserName,
                    MailConstant.networkcredentialsPassword);
                SmtpServer.EnableSsl = true;
                SmtpServer.Send(mail);
                return "1";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }
}
